/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

/**
 *
 * @author Acer
 */
public class daftar_barang extends javax.swing.JPanel {

    /**
     * Creates new form tambah_barang
     */
    public daftar_barang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        A_btn_tambah_barang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        A_btn_refresh = new javax.swing.JButton();
        A_btn_cari_barang = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        A_btn_edit = new javax.swing.JButton();
        A_btn_delete = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1700, 940));
        setMinimumSize(new java.awt.Dimension(1650, 940));
        setPreferredSize(new java.awt.Dimension(1650, 940));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("   DAFTAR BARANG");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, 60));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 400, 40));

        A_btn_tambah_barang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_tambah_barang.setText("TAMBAH BARANG");
        A_btn_tambah_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_tambah_barangActionPerformed(evt);
            }
        });
        jPanel3.add(A_btn_tambah_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 80, 300, 60));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null },
                        { null, null, null, null, null, null, null, null }
                },
                new String[] {
                        "NO.", "KODE BARANG", "NAMA BARANG", "KATEGORI", "HARGA POKOK", "PPN", "KARGA JUAL", "STOK"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1590, 730));

        A_btn_refresh.setBackground(new java.awt.Color(0, 204, 51));
        A_btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_refresh.setText("REFRESH");
        A_btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_btn_refreshActionPerformed(evt);
            }
        });
        jPanel3.add(A_btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 150, 40));

        A_btn_cari_barang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_cari_barang.setText("CARI");
        jPanel3.add(A_btn_cari_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 150, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("CARI");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 150, 40));

        A_btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_edit.setText("EDIT");
        jPanel3.add(A_btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 90, 150, 40));

        A_btn_delete.setBackground(new java.awt.Color(204, 0, 51));
        A_btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A_btn_delete.setText("DELETE");
        jPanel3.add(A_btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 90, 150, 40));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1630, 920));
    }// </editor-fold>//GEN-END:initComponents

    private void A_btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_A_btn_refreshActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_A_btn_refreshActionPerformed

    private void A_btn_tambah_barangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_A_btn_tambah_barangActionPerformed
        // TODO add your handling code here:
        javax.swing.JFrame mainFrame = (javax.swing.JFrame) this.getTopLevelAncestor();

        // Periksa apakah frame tersebut adalah instance dari dashboard_admin
        if (mainFrame instanceof dashboard_admin) {
            // Panggil method publik showTambahBarangPanel() dari dashboard_admin
            ((dashboard_admin) mainFrame).showTambahBarangPanel();
        }
    }// GEN-LAST:event_A_btn_tambah_barangActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_btn_cari_barang;
    private javax.swing.JButton A_btn_delete;
    private javax.swing.JButton A_btn_edit;
    private javax.swing.JButton A_btn_refresh;
    private javax.swing.JButton A_btn_tambah_barang;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
